#define LED1 2
#define HEATER_PWM 25
#define TIP_PWM 33
#define POWER_BUTTON 32
#define LIGHT_PIN 4
#define VOLTAGE_PIN 26
#define CURRENT_PIN 27
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define TFT_BL 0

#define GRID_COLOR TFT_DARKGREY
#define AXIS_COLOR TFT_BLACK
#define WAVE_COLOR TFT_PURPLE
#define BG_COLOR TFT_WHITE
#define SCALE_COLOR TFT_BLACK

#define GRID_X_STEP 24 
#define GRID_Y_STEP 32  
#define GRID_X_DIV 5    
#define GRID_Y_DIV 5    

